version: '3.3'

networks:
  daemons:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24

services:
  raptoreum:
    image: npq7721/raptoreum:1.3.17.0
    container_name: index_raptoreum_node
    ports:
      - "10226:10226"
    volumes:
      - /home/tri/workspace/test/:/raptoreum
    restart: unless-stopped
    networks:
      daemons:
        ipv4_address: 172.16.0.2
    environment:
      PROTX_HASH: e556520a1ba3658d39fbedd05087dbc99aa7797fe45703b7e16db06318c13701
      BOOTSTRAP: "https://bootstrap.raptoreum.com/bootstraps_for_v1.3.17.00/bootstrap-index.tar.xz"
      EXPLORER_LIST: ( 'https://explorer.raptoreum.com/' 'https://explorer.louhintamestarit.fi/' )
      FORCE_BOOTSTRAP: "false"
      CONF: |
        rpcuser=rpcuser
        rpcpassword=rpcpassword
        rpcallowip=127.0.0.1
        rpcbind=127.0.0.1
        server=1
        listen=1
        txindex=1
        addressindex=1
        futureindex=1
        spentindex=1
        timestampindex=1
        maxconnections=125
        smartnodeblsprivkey=1d09c5c84166e04f9d6f590c1f1d5ad58d1410e936f5258fe93c96a15537ec9f
        externalip=184.175.152.237
        addnode=209.151.150.72
        addnode=94.237.79.27
        addnode=95.111.216.12
        addnode=198.100.149.124
        addnode=198.100.146.111
        addnode=5.135.187.46
        addnode=5.135.179.95
        addnode=139.59.7.178
        addnode=167.172.60.177
